### PR TITLE
Improve site

### PR DESCRIPTION
**Pull request by antfu**
Changes
- Use [webfontloader](https://github.com/typekit/webfontloader) to hook on font loading status
- [`font-display: swap`](https://fontsplugin.com/google-fonts-font-display-swap/)
- Make render scrollable
- Make `make_site.js` compactible with Windows \r\n eol

The built `index.html` is not included in this PR.

### CODE REVIEW

**Comment by LingDong-** [comment]
@antfu Nice, thanks!

The font loading thing gave me such a big headache, glad you improved it.

One thing though, I disabled scrolling for the render, because it makes the punctuation marks (`、。`) invisible. (punctuation simply disappears when `overflow` is not `hidden`) I think it is a layout engine bug, but this seems to be the case on Safari, Chrome and FF. Did this happen for you, or did you somehow fixed this issue?

**Comment by antfu** [comment]
> did you somehow fixed this issue?

Yes I think I fixed it (at least on my Chrome)

BTW, since we are already using Netlify to do the build, should we exclude the site folder and make Netlify run the `make_site.js` automatically? So that contributors don't accidentally commit the built html and in PRs we can see the previews too. Would love to update the PR.

 (and do you mind me to introduce the `package.json`? XP

**Comment by LingDong-** [comment]
> Should we exclude the site folder and make Netlify run the make_site.js automatically

That's probably the right way. I didn't know what I was thinking :P

> and do you mind me to introduce the package.json

Sure! We'll need it sooner or later. I didn't add it because it happens that I don't need any library yet, but feel free to add it. For python, we can also add `requirements.txt`, I can work on that.


Thanks!

**Comment by antfu** [comment]
> Netlify run the make_site.js automatically

I have updated the scripts, you can change Netlify build config after this gets merged.

S-20200208-20,46-001

Changes
- make_site.js is now cwd independent (not need to be in ./workflow)
- package.json introduced, with `fs-extra` and `axios`
- `site` is now gitignored
- make_site.js will now download the latest release from github to `site` folder

I have setup Netlify on my fork, here is the demo: https://webfontloader--heuristic-lamport-e72dda.netlify.com/

**Comment by LingDong-** [comment]
Thanks for the improvements,

I switched to the new workflow, and it seems to be working, but

- Vanishing punctuation bug seem to still exist. The number of lines (on the right) that does not have punctuation is equal to the number of hidden lines (on the left). I assume it is because the layout engine assumes that all divs are left-to-right and is trying to be smart by not rendering the stuff it thinks you wouldn't be able to see. 

image

- Is there a way to force netlify to rebuild? When I change the build settings on netlify it doesn't trigger rebuild (wtf), and I have to push some dummy changes to trigger it.

**Comment by antfu** [comment]
> Is there a way to force netlify to rebuild? When I change the build settings on netlify it doesn't trigger rebuild (wtf), and I have to push some dummy changes to trigger it.

As far as I know, no. I just push a new commit for that too 😂

> Vanishing punctuation bug seem to still exist.

Would that exists on Chrome too? My macbook is on the way but due to the virus situation I think I gonna wait for a while longer :|

**Comment by LingDong-** [comment]
> Would that exists on Chrome too?

Yeah... the above screenshot is Chrome actually. I guess we have to get scrolling working eventually, if we are to display the wenyan book with the font. Since you can't reproduce, let me look into it!

> gonna wait for a while longer

No hurry, be safe :)

**Comment by LingDong-** [comment]
Vanishing punctuation is fixed: 65fb45358a9071959bc39fd6639aa8fe4d2672b0

The cause is that the height of the punctuation spans are 0 (as they should be). Theoretically they should still display since `overflow` is not `hidden`. And it works correctly when there is no scrolling. But somehow when combined with the scrolling it screws up the browsers mind.

The hack is to make the height 0.01.

**Comment by LingDong-** [comment]
Hi @antfu,

I thought I could add a nice little loading animation while the font is loading:

qiji007

Only problem is that `WebFont.load` is blocking render, so the loading animation does not play until the font is loaded :P

Just wondering if you know more about web fonts more than me... But otherwise I can look into it. Worst case perhaps is to show a GIF...

See

```
/workflow/make_site_w_loader.js
/workflow/loading_anim.js
```

Thanks!

**Comment by antfu** [comment]
@LingDong- The animation looks fantastic!

> Only problem is that WebFont.load is blocking render

I don't think it will block rendering. I will try some expirement fist :)

**Pull request merged**
